=== liquid667/liquid-examples/src/infinispan/sharpup/src/main/resources/PSAPData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="PSAPData">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="psap" type="data" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="data">
		<xs:sequence>
				<xs:element name="eventId" type="xs:string" />
				<xs:element name="type" type="psapType " />
				<xs:element name="name" type="xs:string" />
				<xs:element name="description" type="xs:string" />
				<xs:element name="position" type="position" />
				<xs:sequence>
					<xs:element name="emailAddress" type="emailAdresses" />
				</xs:sequence>
				<xs:element name="phoneNumbers" type="phoneNumbers" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="phoneNumbers">
		<xs:sequence>
			<xs:element name="primaryPhoneNumber" type="xs:string" />
			<xs:element name="primarySIPLink" type="xs:string" />
			<xs:element name="secondaryPhoneNumber" type="xs:string" />
			<xs:element name="secondarySIPLink" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="position">
		<xs:sequence>
			<xs:element name="latitude" type="xs:string" />
			<xs:element name="longitude" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="psapType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="police" />
			<xs:enumeration value="hospital" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Error">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="code" type="xs:int" />
				<xs:element name="message" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="emailAdresses">
		<xs:sequence>
			<xs:element name="emailAddress" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== liquid667/liquid-examples/src/infinispan/sharpup/src/main/resources/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<PSAPData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PSAPData.xsd">
  <psap>
    <eventId>eventId</eventId>
    <type>police</type>
    <name>name</name>
    <description>description</description>
    <position>
      <latitude>latitude</latitude>
      <longitude>longitude</longitude>
    </position>
    <emailAddress>
      <emailAddress>emailAddress</emailAddress>
      <emailAddress>emailAddress</emailAddress>
      <emailAddress>emailAddress</emailAddress>
    </emailAddress>
    <phoneNumbers>
      <primaryPhoneNumber>primaryPhoneNumber</primaryPhoneNumber>
      <primarySIPLink>primarySIPLink</primarySIPLink>
      <secondaryPhoneNumber>secondaryPhoneNumber</secondaryPhoneNumber>
      <secondarySIPLink>secondarySIPLink</secondarySIPLink>
    </phoneNumbers>
  </psap>
  <psap>
    <eventId>eventId</eventId>
    <type>police</type>
    <name>name</name>
    <description>description</description>
    <position>
      <latitude>latitude</latitude>
      <longitude>longitude</longitude>
    </position>
    <emailAddress>
      <emailAddress>emailAddress</emailAddress>
      <emailAddress>emailAddress</emailAddress>
      <emailAddress>emailAddress</emailAddress>
    </emailAddress>
    <phoneNumbers>
      <primaryPhoneNumber>primaryPhoneNumber</primaryPhoneNumber>
      <primarySIPLink>primarySIPLink</primarySIPLink>
      <secondaryPhoneNumber>secondaryPhoneNumber</secondaryPhoneNumber>
      <secondarySIPLink>secondarySIPLink</secondarySIPLink>
    </phoneNumbers>
  </psap>
  <psap>
    <eventId>eventId</eventId>
    <type>police</type>
    <name>name</name>
    <description>description</description>
    <position>
      <latitude>latitude</latitude>
      <longitude>longitude</longitude>
    </position>
    <emailAddress>
      <emailAddress>emailAddress</emailAddress>
      <emailAddress>emailAddress</emailAddress>
      <emailAddress>emailAddress</emailAddress>
    </emailAddress>
    <phoneNumbers>
      <primaryPhoneNumber>primaryPhoneNumber</primaryPhoneNumber>
      <primarySIPLink>primarySIPLink</primarySIPLink>
      <secondaryPhoneNumber>secondaryPhoneNumber</secondaryPhoneNumber>
      <secondarySIPLink>secondarySIPLink</secondarySIPLink>
    </phoneNumbers>
  </psap>
</PSAPData>
